server:
  port: 8002 #注册中心端口
eureka:
  instance:
    hostname: server2
#    prefer-ip-address: true #开启用IP来指定服务地址，默认是false,所以要在hosts文件里加上 127.0.0.1 server2
  client:
    register-with-eureka: true #自己注册以下两个服务上
    fetch-registry: false #不需要去检索服务
    service-url:
      defaultZone:  http://server1:8001/eureka/,http://server4:8004/eureka/
spring:
  application:
    name: server