
server:
  port: 8001 #注册中心端口
eureka:
  instance:
    hostname: server1
  client:
    register-with-eureka: true #自己注册以下两个服务上
    fetch-registry: false #不需要去检索服务
    service-url:
      defaultZone:  http://server2:8002/eureka/,http://server4:8004/eureka/
spring:
  application:
    name: server
