server:
  port: 8888
spring:
  application:
    name: zfz-gateway
zuul:
  routes:
#     传统方式
#    api-a-url:
#      path: /api-a-url/**
#      url:  http://localhost:8011/
#     面向服务方式
    api-user-url:
      path: /zfz-user/**
      serviceId:  zfz-user
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8001/eureka/ #注册中心
