eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: zuulservice
zuul:
  routes:
    api-a:
      path: /aaa/**
      serviceId: service-client1
    api-b:
      path: /bbb/**
      serviceId: feignservice