server:
  port: 8022  #服务端口

# REDIS (RedisProperties)
eureka:
  client:
    serviceUrl:
      #      defaultZone:  http://192.168.88.204:8001/eureka/
      defaultZone:  http://192.168.88.204:8001/eureka/,http://192.168.88.204:8002/eureka/,http://192.168.88.204:8004/eureka/ #注册中心集群
spring:
  application:
    name: zfz-wealth
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost
    port: 6379
    password:
    timeout: 1000ms

  # Redis服务器地址
  #spring.redis.host=localhost
  # Redis服务器连接端口
  #spring.redis.port=6379
  # Redis服务器连接密码（默认为空）
  #spring.redis.password=qpc_redis
  # 连接池最大连接数（使用负值表示没有限制）
  #spring.redis.pool.max-active=8
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #spring.redis.pool.max-wait=-1
  # 连接池中的最大空闲连接
  #spring.redis.pool.max-idle=8
  # 连接池中的最小空闲连接
  #spring.redis.pool.min-idle=0
  # 连接超时时间（毫秒）
  #spring.redis.timeout=0

  datasource:
    url: jdbc:mysql://localhost:3308/zfz?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: rootroot
    driverClassName:  com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #dataSource Pool configuration
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    exceptionSorter: true
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    #     connectionProperties: druid.stat.merge
    #     Sql: true
    #     druid:
    #       stat:
    #       slowSqlMillis: 500
    useGlobalDataSourceStat: true
mybatis:
  mapperLocations: classpath:mapper/*.xml