spring:
  application:
    name: zfz-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/github2683/zfzgb
          search-paths: server/config/zfz-user
          #          search-paths: server/config/server,server/config/zfz-gateway,server/config/zfz-user,server/config/zfz-wealth
          username: 1009600394@qq.com
          password: 851121123abc
        #prefix: application
server:
  port: 9999
